version: '3.8'

services:
  webhook:
    build:
      context: .
    container_name: clickup-webhook-fastify
    env_file: .env
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/tickets/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    networks:
      - webhook-network

networks:
  webhook-network:
    driver: bridge